//
//  HallMsgDefine.h
//  SlotsGame
//
//  Created by Davinci on 14-8-20.
//
//

#ifndef SlotsGame_HallMsgDefine_h
#define SlotsGame_HallMsgDefine_h



/**接收消息的基准值**/
#define OGID_MSGBASE_TEXASPOKER_GAMEBASE  	  134217728
/**发送消息基准值**/
#define OGID_MSGBASE_TEXAS_SLOTS  			  12345

/********************大厅和游戏通道消息********************/
#define AISLE_TEXAS_SLOTS_CLOSEDOUBLEUI 		   	200 				//通知游戏关闭比倍UI
#define AISLE_TEXAS_SLOTS_ENTERFRAME 			   	201 				//enterFrame消息
#define AISLE_TEXAS_SLOTS_PET 					   	202 				//发送战斗状态的宠物到游戏中
#define AISLE_TEXAS_SLOTS_CLOSEFIGHT 			   	203 				//发送关闭宠物战斗界面
#define AISLE_TEXAS_SLOTS_UPDATEDPLAYERINFO 	   	204 				//通知游戏更新玩家信息
#define AISLE_TEXAS_SLOTS_OPENMODULE 			   	205 				//通知游戏打开新的module
#define AISLE_TEXAS_SLOTS_CLEARROOM 			  	206 				//清理房间信息
#define AISLE_TEXAS_SLOTS_MUSICON 				  	207 				//房间音效开关
#define AISLE_TEXAS_SLOTS_FIGHTEND                	208 				//宠物战斗结束处理
#define AISLE_TEXAS_SLOTS_BROADERMSG 			  	209 				//广播jp中奖消息


/************************请求消息***************************/
#define OGID_TEXAS_SLOTS_IDLE 					   (OGID_MSGBASE_TEXAS_SLOTS + 0) 				//心跳消息
#define OGID_TEXAS_SLOTS_SERVER 				   OGID_MSGBASE_TEXAS_SLOTS + 1 				//请求服务器
#define OGID_TEXAS_SLOTS_LOGIN                     OGID_MSGBASE_TEXAS_SLOTS + 2 				//登录验证
#define OGID_TEXAS_SLOTS_JOINROOM 				   OGID_MSGBASE_TEXAS_SLOTS + 3 				//进入房间
#define OGID_TEXAS_SLOTS_EXITGAME 				   OGID_MSGBASE_TEXAS_SLOTS + 4 				//退出房间

#define OGID_TEXAS_SLOTS_REQPETLIST 			   OGID_MSGBASE_TEXAS_SLOTS + 5 				//请求宠物列表消息
#define OGID_TEXAS_SLOTS_REQPETRESET 			   OGID_MSGBASE_TEXAS_SLOTS + 6 		        //请求宠物属性重置
#define OGID_TEXAS_SLOTS_REQPETFIGHT 			   OGID_MSGBASE_TEXAS_SLOTS + 7 				//请求宠物战斗
#define OGID_TEXAS_SLOTS_REQPETPACK 			   OGID_MSGBASE_TEXAS_SLOTS + 8 				//请求宠物列表消息


#define OGID_TEXAS_SLOTS_REQRANKING 			   OGID_MSGBASE_TEXAS_SLOTS + 9 				//请求排行榜消息

#define OGID_TEXAS_SLOTS_REQMAILS 				   OGID_MSGBASE_TEXAS_SLOTS + 10 				//请求邮件消息
#define OGID_TEXAS_SLOTS_REQMAILSTATE 			   OGID_MSGBASE_TEXAS_SLOTS + 11 				//请求修改邮件状态消息
#define OGID_TEXAS_SLOTS_PETRESOLVE 			   OGID_MSGBASE_TEXAS_SLOTS + 12 				//宠物分解
#define OGID_TEXAS_SLOTS_GUIDEOVER                 OGID_MSGBASE_TEXAS_SLOTS + 13 				//新手引导完成

#define OGID_TEXAS_SLOTS_REQAWARD 				   OGID_MSGBASE_TEXAS_SLOTS + 14 				//领取新手奖励
#define OGID_TEXAS_SLOTS_REQSHOPITEM 			   OGID_MSGBASE_TEXAS_SLOTS + 15 				//请求商品数据
#define OGID_TEXAS_SLOTS_REQBUYITEM 			   OGID_MSGBASE_TEXAS_SLOTS + 16 				//请求购买商品数据
#define OGID_TEXAS_SLOTS_REQPETCOMPOSE             OGID_MSGBASE_TEXAS_SLOTS + 17 				//请求宠物合成
#define OGID_TEXAS_SLOTS_REQCOMPOSE 			   OGID_MSGBASE_TEXAS_SLOTS + 18 				//请求宠物合成方案
#define OGID_TEXAS_SLOTS_REQPETRESOLVESCHEME 	   OGID_MSGBASE_TEXAS_SLOTS + 19 				//请求宠物分解方案

#define OGID_TEXAS_SLOTS_REQLOGINAWARD             OGID_MSGBASE_TEXAS_SLOTS + 20 				//请求登录奖励
#define OGID_TEXAS_SLOTS_REQPETRETURNAWARD         OGID_MSGBASE_TEXAS_SLOTS + 21 				//请求宠物互动
#define OGID_TEXAS_SLOTS_REQFIGHTAWARD             OGID_MSGBASE_TEXAS_SLOTS + 55 				//请求宠物战斗奖励
#define AISLE_TEXAS_SLOTS_JACKPOTLIST 			   OGID_MSGBASE_TEXAS_SLOTS + 56 				//请求jp数据
#define OGID_TEXAS_SLOTS_BINDPHONE                 OGID_MSGBASE_TEXAS_SLOTS + 22 				//是否绑定
#define OGID_TEXAS_SLOTS_GETCODE 			       OGID_MSGBASE_TEXAS_SLOTS + 23 				//获取验证码
#define OGID_TEXAS_SLOTS_GETCODEOK                 OGID_MSGBASE_TEXAS_SLOTS + 24 				//输入验证码

#define OGID_TEXAS_SLOTS_REQGAMESTRT               OGID_MSGBASE_TEXAS_SLOTS + 50				// 开始转动游戏
#define OGID_TEXAS_SLOTS_REQDOUBLEGAME             OGID_MSGBASE_TEXAS_SLOTS + 51				// 开始比倍游戏
#define OGID_TEXAS_SLOTS_REQDOUBLEGETGOLD          OGID_MSGBASE_TEXAS_SLOTS + 52				// 比倍收分消息
#define OGID_TEXAS_SLOTS_REQPETFIGHT2               OGID_MSGBASE_TEXAS_SLOTS + 53				// 接收宠物战斗
#define OGID_TEXAS_SLOTS_REQPETFLEE              OGID_MSGBASE_TEXAS_SLOTS + 54				// 接收宠物逃跑

/***********************接收消息******************************/
#define OGID_TEXAS_SLOTS_LINK 					   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 1 		//接收服务器ip、端口
#define OGID_TEXAS_SLOTS_ROLEMSG 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 2 		//返回玩家信息
#define OGID_TEXAS_SLOTS_ROOMLIST 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 3 		//接收房间列表
#define OGID_TEXAS_SLOTS_ROOMSITE 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 4 		//接收房间配置信息
#define OGID_TEXAS_SLOTS_PLAYERINFO 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 5 		//更新玩家信息
#define OGID_TEXAS_SLOTS_PETLIST 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 7 		//请求宠物列表消息
#define OGID_TEXAS_SLOTS_BORADCAST                 OGID_MSGBASE_TEXASPOKER_GAMEBASE + 8 		//接收广播信息
#define OGID_TEXAS_SLOTS_GIFTPET 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 9 		//接收系统赠送宠物信息
#define OGID_TEXAS_SLOTS_PETRESET 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 10 		//接收宠物属性重置
#define OGID_TEXAS_SLOTS_BOSSINFO 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 11 		//接收boss配置信息
#define OGID_TEXAS_SLOTS_PETPACK 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 12 		//接收宠物背包消息
#define OGID_TEXAS_SLOTS_RANKINGDATA 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 13 		//接收排行榜数据
#define OGID_TEXAS_SLOTS_PETUPDATEDMSG             OGID_MSGBASE_TEXASPOKER_GAMEBASE + 14 		//接收宠物更新消息
#define OGID_TEXAS_SLOTS_CLOSEMODULE 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 15 		//接收关闭Module消息


#define OGID_TEXAS_SLOTS_ACKMAILS 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 16 		//接收邮件消息
#define OGID_TEXAS_SLOTS_ACKMAILCHARGE             OGID_MSGBASE_TEXASPOKER_GAMEBASE + 17 		//接收邮件附件消息
#define OGID_TEXAS_SLOTS_ACKITEMS 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 18 		//接收道具消息
#define OGID_TEXAS_SLOTS_ACKNEWMAIL 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 19 		//接收新邮件消息

#define OGID_TEXAS_SLOTS_ACKGUIDEAWARD             OGID_MSGBASE_TEXASPOKER_GAMEBASE + 20 		//接收新手奖励消息
#define OGID_TEXAS_SLOTS_ACKPROPSCONSUMPTION 	   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 21 		//接收道具消耗消息
#define OGID_TEXAS_SLOTS_ACKSHOPLIST 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 22 		//接收商城商品消息
#define OGID_TEXAS_SLOTS_ACKPETRESOLVE             OGID_MSGBASE_TEXASPOKER_GAMEBASE + 23 		//宠物分解返回结果
#define OGID_TEXAS_SLOTS_ACKPETCOMPOSE             OGID_MSGBASE_TEXASPOKER_GAMEBASE + 24 		//接收宠物合成结果
#define OGID_TEXAS_SLOTS_ACKSCHEME                 OGID_MSGBASE_TEXASPOKER_GAMEBASE + 25 		//接收宠物合成方案
#define OGID_TEXAS_SLOTS_ACKRESOLVESCHEME 		   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 26 		//接收宠物分解方案

#define OGID_TEXAS_SLOTS_ACKJPMESSAGE 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 27 		//玩家登录接收JP中奖消息
#define OGID_TEXAS_SLOTS_ACKLOGINAWARD             OGID_MSGBASE_TEXASPOKER_GAMEBASE + 28 		//返回登陆中奖信息
#define OGID_TEXAS_SLOTS_ACKLOGINREWARD 		   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 29 		//接收抽奖消息
#define OGID_TEXAS_SLOTS_OGREQNOTICE 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 30 		//系统公告
#define OGID_TEXAS_SLOTS_ACKDOUBLEPLUS             OGID_MSGBASE_TEXASPOKER_GAMEBASE + 31 		//比倍星级加成
#define OGID_TEXAS_SLOTS_ACKPETRETURNAWARD         OGID_MSGBASE_TEXASPOKER_GAMEBASE + 34 		//宠物互动结果
#define OGID_TEXAS_SLOTS_ACKJPSTAR                 OGID_MSGBASE_TEXASPOKER_GAMEBASE + 35 		//JP明星

#define OGID_TEXAS_SLOTS_ACKBINDPHONE 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 36 		//返回是否绑定
#define OGID_TEXAS_SLOTS_ACKGETCODE 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 37 		//返回验证码
#define OGID_TEXAS_SLOTS_ACKGETCODEOK 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 38 		//输入验证码


#define OGID_TEXAS_SLOTS_ACKJACKPOTLIST 		   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 59 		//接收jackpot数据
#define OGID_TEXAS_SLOTS_DOUBLEJP 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 60 		//接收比倍jp消息

/***********************游戏内消息*****************************/
#define OGID_TEXAS_SLOTS_GAMERESULT 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 50 		//接收游戏结果
#define OGID_TEXAS_SLOTS_JACKPOT 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 51 		//更新奖池消息
#define OGID_TEXAS_SLOTS_DOUBLEGAME 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 52 		//接收比倍游戏结果
#define OGID_TEXAS_SLOTS_COLLECTION 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 53 		//接收收分消息
#define OGID_TEXAS_SLOTS_FIGHTRESULT 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 55 		//接收宠物战斗结果消息
#define OGID_TEXAS_SLOTS_FIGHTREWARD 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 56 		//接收战斗奖励消息
#define OGID_TEXAS_SLOTS_STOPGAME 				   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 57 		//接收玩家止损消息
#define AISLE_TEXAS_SLOTS_DOUBLESTART 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 58 		//比倍星级加成数据

#define ACK_SEVER_JPHALL 			   OGID_MSGBASE_TEXASPOKER_GAMEBASE + 39 		//



#define GAME_LAYER_BACK 331579
#define BIBEI_LAYER_BACK 331580
#define SET_ALL_THINGS_RUN 331581
#define CREATE_ROLE_EVENT 331582//创建角色事件
#define CREATE_ROLE_EVENT_RET "331583"//创建角色事件返回
#define ERR_RET 331584//


#endif
